name = "gleaming_shades"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
lustre = ">= 5.4.0 and < 6.0.0"
modem = ">= 2.1.2 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 2.3.1 and < 3.0.0"

[tools.lustre.html]
stylesheets = [
  { href = "./cards.css" },
  { href = "./common.css" },
]
